services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "data-sensors:1:1" # Automatically create topic 'data-sensors'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer:
    build: ./Producer
    depends_on:
      - kafka
    volumes:
      # Map the data folder from your laptop into the container
      - ./NASA_Bearing_Data:/app/NASA_Bearing_Data


  spark:
    build: ./Processing
    environment:
      - SPARK_MODE=master
    depends_on:
      - kafka
    ports:
      - "4040:4040" # Spark UI
    volumes:
      - ./Processing:/app/Processing
      - ./NASA_Bearing_Data:/app/NASA_Bearing_Data
      - ./Processing/models:/app/models

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: bigdatauser
      POSTGRES_PASSWORD: group5
      POSTGRES_DATABASE: predictive_maintenance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./postgresql_init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: